{% set name = "abi3info" %}
{% set version = "2025.11.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/woodruffw/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 588d4f869b63766e1583ab55acc886297de23ef8328717a1d93dd971aa7425b0

build:
  skip: true # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test
    - pyproject.toml
  imports:
    - abi3info
  commands:
    - pip check
    - pytest -vv
  requires:
    - pip
    - python
    - pytest

about:
  home: https://pypi.org/project/abi3info
  summary: A library for abi3 and other CPython API information
  description: |
    abi3info exposes information about CPython's "limited API"
    (including the stable ABI, called abi3) as a Python library.
  dev_url: https://github.com/woodruffw/abi3info
  doc_url: https://woodruffw.github.io/abi3info/abi3info.html
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
